### ISSUE TITLE
Blogs links are not showing sidebar of Spina

### ISSUE THREAD

**Issue by anuj-dhanju** [SpinaCMS/spina-blog#15]
Hi Team
I have installed latest Spina CMS and Installed spina-blog. Everything is working fine if i put spina-blog url directly in browser, But spina-blog navigation is not showing in sidebar. May be I am missing something in configuration and its not an issue. 
Thanks for building this great open-source. 
Thanks

**Comment by simmerz** [comment]
Can you clarify how you've installed `spina-blog`?

**Comment by anuj-dhanju** [comment]
Hi Simmerz
Thanks for quick response. 

Gemfile:-
gem 'spina', github: 'spinacms/spina'
gem 'spina-blog', github: 'spinacms/spina-blog'

And after bundle , I run this rails g spina_blog:install >
Please let me know I you any question. 

Thanks

**Comment by simmerz** [comment]
And do you have a list of plugins you have installed in your theme initialiser? If so, you'll need to add the blog to it, but the preference is not to have that at all and allow the engine to initialise itself.

**Comment by anuj-dhanju** [comment]
thanks Simmerz 
after adding theme.plugins = ['reviews', 'blog'] in theme initialiser, its working.
