### ISSUE TITLE
Spina blog for Rails Rails 6.0.3.2 && Spina 2..0

### ISSUE THREAD

**Issue by bri-vax** [SpinaCMS/spina-blog#19]
Impossible to see blog page or to access to post in admin panel.
![rails 6 0](https://user-images.githubusercontent.com/37874010/86517607-87889300-be2a-11ea-94c5-0a52c8cada85.JPG)

**Comment by simmerz** [comment]
Are you using the spina_2_0 branch?

**Comment by bri-vax** [comment]
yes
