### ISSUE TITLE
Archive index page?

### ISSUE THREAD

**Issue by wakproductions** [SpinaCMS/spina-blog#43]
As far as I can tell, there is no archive index page. You have to specify a year and month to filter past posts. Please enhance my understanding if this is incorrect. I will consider opening a PR to build such a page if no such feature exists.

**Comment by wakproductions** [comment]
So the solution that I've come up with that works around this is to just have a widget with links to each archive year. My code looks like this:

```
# components/spina/blog/archived_posts_widget_component.rb

module Spina
  module Blog
    class ArchivedPostsWidgetComponent < Spina::ApplicationComponent

      PostsYear = Struct.new(
        :year,
        :count,
        keyword_init: true
      ) do
        include Spina::Engine.routes.url_helpers

        def path
          blog_archive_posts_path(year)
        end

      end

      def initialize
        @posts_years =
          Spina::Blog::Post
            .live
            .pluck(:published_at)
            .map(&:year)
            .tally
            .map do |year, count|
              PostsYear.new(year: year, count: count)
            end
      end

    end
  end
end

# archived_posts_widget_component.html.erb
<ul class="spina-blog-archived-posts-widget">
  <% @posts_years.each do |py| %>
    <li class="spina-blog-archived-posts-widget-year"><%= link_to(py.year, py.path) %> (<%= py.count %>)</li>
  <% end %>
</ul>

```

That generates a near little link navigation that looks like this:
![image](https://github.com/SpinaCMS/spina-blog/assets/1912237/e74405d3-400d-4dd8-b8c8-4002edc67521)


lmk if you like this feature and I'll open a PR to move this into the gem.

**Comment by simmerz** [comment]
I'd prefer this to be a single database query selecting the year and the count, thereby avoiding the map. But feel free to raise a PR for that :)

**Comment by wakproductions** [comment]
> I'd prefer this to be a single database query selecting the year and the count, thereby avoiding the map. But feel free to raise a PR for that :)

The reason for the map was to keep it DB platform agnostic. To do it in a single query, I'd have to use 

```
ActiveRecord::Base.connection.execute(
  "select extract('Year' from published_at) as published_at_year, count(extract('Year' from published_at)) from spina_blog_posts group by published_at_year;"
)
```

That would be Postgres-specific code. As far as I am aware, Rails does not have an aggregation method that could extract the year from `published_at`.

**Comment by wakproductions** [comment]
The widget satisfied my current needs.
