### ISSUE TITLE
Template reference problem from `views/default/blog/posts/`

### ISSUE THREAD

**Issue by wakproductions** [SpinaCMS/spina-blog#49]
@aseroff I discovered a new issue that occurs when I move my blog templates from `views/spina/blog/posts` (old location) to `views/default/blog/posts` (recommended new location).

My `blog/posts/index.slim` looks like this:
```
    #blog-index.col-lg-8
      / Have to do the limiting to the first 20 here instead of the controller
      .posts= render(@posts.first(20))
```

When this file is in the old location it properly renders the `_post.slim` template for each `@post`. When move all my templates to the new location `views/default/blog/posts` it renders the wrong individual `_post` template. Instead of rendering the custom one I made which should override, it renders `views/spina/blog/posts/_post.html.erb` from within the rubygem instead. :trollface:

**Comment by aseroff** [comment]
> @aseroff I discovered a new issue that occurs when I move my blog templates from `views/spina/blog/posts` (old location) to `views/default/blog/posts` (recommended new location).
> 
> My `blog/posts/index.slim` looks like this:
> ```
>     #blog-index.col-lg-8
>       / Have to do the limiting to the first 20 here instead of the controller
>       .posts= render(@posts.first(20))
> ```
> 
> When this file is in the old location it properly renders the `_post.slim` template for each `@post`. When move all my templates to the new location `views/default/blog/posts` it renders the wrong individual `_post` template. Instead of rendering the custom one I made which should override, it renders `views/spina/blog/posts/_post.html.erb` from within the rubygem instead. :trollface: 

`render partial: 'default/blog/posts', collection: @posts` should do it

**Comment by aseroff** [comment]
@wakproductions can you try this branch and see if overriding `to_partial_path` allows you to continue using the shorthand render? https://github.com/aseroff/spina-blog/tree/magic-lookup-for-posts-fix

**Comment by aseroff** [comment]
@wakproductions Can you try this branch and see if it allows you to continue using `render @posts`?

https://github.com/aseroff/spina-blog/tree/default-post-partial-fix

**Comment by wakproductions** [comment]
Nope.

![image](https://github.com/SpinaCMS/spina-blog/assets/1912237/319147fe-7883-4845-bf25-0bc8bcc81743)

My app is currently working on commit `0fccc9358a0bec69676a5ae918bec1af91d7b66b`. I got that working, not going to invest more time to this. I'm mostly concerned about other people using this gem, upgrading, and finding their code broken.
